#' Update metadata tables
#'
#' @param con A database connection
#' @param field_meta A data frame matching the structure for field metadata generated by \code{create_metadata_tables()}
#' @param table_meta A data frame matching the structure for table metadata generated by \code{create_metadata_tables()}
#' @param source_meta An optional data frame matching the structure for source metadata generated by \code{create_metadata_tables()}
#'
#' @export
#'
#' @importFrom utils menu
#' @import DBI
#' @importFrom crayon green
#' @importFrom cli symbol
#'
update_metadata <- function(con, field_meta, table_meta, source_meta = NULL){


  stopifnot(is.data.frame(field_meta))
  stopifnot(is.data.frame(table_meta))

  # check for name mismatches -----------------------------------------------

  field_cols <- c("table_name", "column_name", "description", "data_source")
  table_cols <- c("table_name", "table_schema", "table_description", "last_update")
  source_cols <- c("data_source", "table_name", "table_schema", "source_year", "update_cadence")

  stopifnot(all(names(field_meta) %in% field_cols))
  stopifnot(all(field_cols %in% names(field_meta)))

  stopifnot(all(names(table_meta) %in% table_cols))
  stopifnot(all(table_cols %in% names(table_meta)))

  if (!is.null(source_meta)){
    stopifnot(all(names(source_meta) %in% source_cols))
    stopifnot(all(source_cols %in% names(source_meta)))
  }

  # check for conflicts -------------------------------------------------------

  ## check if combination of column and table name already exists in meta table ----
  field_check_q <- glue::glue_sql("select count(*) from metadata.field_metadata where column_name in ({field_meta$column_name*})
                                  and table_name in ({field_meta$table_name*});", .con = con)

  field_check <- as.numeric(DBI::dbGetQuery(con, field_check_q)$count)

  if (field_check > 0){
    ans <- utils::menu(c(paste(crayon::green(cli::symbol$tick), 'Yes'),
                         paste(crayon::red(cli::symbol$cross), 'No')),
                       title = "This will overwrite existing metadata in the `field_metadata` table. Do you wish to proceed?")
  } else {
    ans <- 1
  }

  ## check if combination of table name and table schema exists in table meta ----
  table_check_q <- glue::glue_sql("select count(*) from metadata.table_metadata where table_name in ({table_meta$table_name*})
                                  and table_schema in ({table_meta$table_schema*});", .con = con)

  table_check <- as.numeric(DBI::dbGetQuery(con, table_check_q)$count)

  if (table_check > 0){
    ans <- utils::menu(c(paste(crayon::green(cli::symbol$tick), 'Yes'),
                         paste(crayon::red(cli::symbol$cross), 'No')),
                       title = "This will overwrite existing metadata in the `table_metadata` table. Do you wish to proceed?")
  } else {
    ans <- 1
  }

  ## check if source meta exists ----------------------------------------

  if (!is.null(source_meta)){

    source_check_q <- glue::glue_sql("select count(*) from metadata.source_metadata where data_source in ({source_meta$data_source*});",
                                     .con = con)

    source_check <- as.numeric(DBI::dbGetQuery(con, source_check_q)$count)

    if (source_check > 0){
      ans <- utils::menu(c(paste(crayon::green(cli::symbol$tick), 'Yes'),
                           paste(crayon::red(cli::symbol$cross), 'No')),
                         title = "This will overwrite existing metadata in the `source_metadata` table. Do you wish to proceed?")
    } else {
      ans <- 1
    }

  }

  if (ans != 1){
    stop_quietly("Cancelled writing metdata")
  }


  # write field metadata ----------------------------------------------------

  cleanup_field_query <- glue::glue_sql("delete from metadata.field_metadata where column_name in ({field_meta$column_name*})
                                  and table_name in ({field_meta$table_name*});", .con = con)

  execute_on_postgres(con, cleanup_field_query)

  DBI::dbWriteTable(con, DBI::Id(schema = 'metadata', table = 'field_metadata'), field_meta, append = TRUE)


  # write table meta -------------------------------------------------------

  cleanup_table_query <- glue::glue_sql("delete from metadata.table_metadata where table_name in ({table_meta$table_name*})
                                  and table_schema in ({table_meta$table_schema*});", .con = con)

  execute_on_postgres(con, cleanup_table_query)
  dbWriteTable(con, DBI::Id(schema = 'metadata', table = 'table_metadata'), table_meta, append = TRUE)


  # write source meta -------------------------------------------------------
  if (!is.null(source_meta)){

    source_cleanup_query <- glue::glue_sql("delete from metadata.source_metadata where data_source in ({source_meta$data_source*});",
                                           .con = con)

    execute_on_postgres(con, source_cleanup_query)

    DBI::dbWriteTable(con, DBI::Id(schema = 'metadata', table = 'source_metadata'), source_meta, append = TRUE)

  }

  cat(crayon::green(cli::symbol$tick), " Metadata succesfully updated", sep = "")

}

