#' Write data to the database. Optionally update metadata tables in the process
#'
#' @param con A database connection
#' @param name Name of the table to write to
#' @param dta A data frame or sf data frame
#' @param overwrite If `TRUE`, overwrite an existing table
#' @param append If `TRUE`, append to an existing table
#' @param spatial If `TRUE`, write as spatial data
#' @param field_meta An optional data frame matching the structure for field metadata generated by `create_metadata_tables()`
#' @param table_meta An optional data frame matching the structure for table metadata generated by `create_metadata_tables()`
#' @param source_meta An optional data frame matching the structure for source metadata generated by `create_metadata_tables()`
#'
#' @export
#'
#' @importFrom sf st_write
#' @importFrom DBI dbWriteTable
#'

write_db <- function(con, name, dta, overwrite = FALSE, append = FALSE, spatial = FALSE, field_meta = NULL, table_meta = NULL, source_meta = NULL){

  if (spatial){

    if (!'sf' %in% class(dta)){
      stop('`spatial` is TRUE, but `dta` is not of class sf', call. = FALSE)
    }

    sf::st_write(dta, con, name, delete_dsn = overwrite, append = append)
  }

  if (!spatial){
    DBI::dbWriteTable(con, name, dta, overwrite = overwrite, append = append)
  }

  if (!is.null(field_meta) | !is.null(table_meta)){

    # if (is.null(table_meta)){
    #   stop("Both field and table metadata are required to update metadata")
    # }

    update_metadata(con, field_meta, table_meta, source_meta)

  }

  return(invisible(name))

}


#' Open a connection and write a table to specific schema
#'
#' A simpel wrapper function around open a connexion to the DB data, write a table and 
#' close the connexion.
#'
#' @param schema Name of the schema to write
#' @param name Name of the table to write
#' @param dta A data frame that will be wrote
#' @param overwrite `TRUE` by default, overwrite an existing table
#' @param DB_instance default `data`, passed to the connection to specify DB instance
#' @param ... other arguments for DBI::dbWriteTable()
#' @export
#'
#' @importFrom DBI dbWriteTable
#' @importFrom DBI dbDisconnect
#'

simple_write_db <- function(schema, name, dta, overwrite = TRUE,
                            DB_instance = "data", ...) {
  con <- cori.db::connect_to_db(schema, dbname = DB_instance)
  on.exit(DBI::dbDisconnect(con))
  DBI::dbWriteTable(con, name, dta, overwrite = TRUE, ...)
}

#'  Write data to the database. But ask before!
#'
#' Do not work with spatial data!
#' Use connect_to_db() default hence write to data instance
#'
#' @param schema Name of the schema to write
#' @param name Name of the table to write
#' @param dta A data frame that will be wrote
#' @param overwrite `TRUE` by default, overwrite an existing table
#' @param DB_instance default `data`, passed to the connection to specify DB instance
#' @param ... other arguments for DBI::dbWriteTable()
#' @export
#'
#' @importFrom DBI dbWriteTable
#' @importFrom DBI dbDisconnect
#'

safely_write_to_db <- function(schema, name, dta, overwrite = TRUE,
                               DB_instance = "data", ...) {

  write_prompt <- paste0("Are you sure you want to overwrite",
                         schema, ".", name, " in the database? (yes/no): ")
  write_confirmation <- readline(prompt = write_prompt)

  if (tolower(write_confirmation) == "yes") {
    message(paste0("You chose to overwrite ", schema, ".", name, "\n"))
    simple_write_db(schema, name, dta, overwrite = TRUE,
                    DB_instance = DB_instance, ...)
  } else {
    message("You chose not to write to the database")
  }
}

#' Function factory to save you an argument (schema)
#'
#' @param schema Name of the schema
#' @param DB_instance default `data`, passed to the connection to specify DB instance
#' @param ... other arguments for DBI::dbWriteTable()
#' @export
#'
#' @examples
#' 
#' \dontrun{
#' # This is a function factory that takes a schema
#' # and returns a wrapper function, so first step is defiining
#' # the callback and passing it to generate the wrapper function:
#' write_staging <- prepare_to_write_table("staging")
#'
#' # ...then use it:
#' write_staging("mtcars", mtcars, overwrite = TRUE)
#'
#' # ... which should prompt the user before running the callback function to write data to db
#' }

prepare_to_write_table <- function(schema, DB_instance = "data", ...) {
  force(schema)
  force(DB_instance)
  function(name, dta) {
    safely_write_to_db(schema, name, dta, overwrite = TRUE,
                       DB_instance = DB_instance, ...)
  }
}