#' Write data to the database. Optionally update metadata tables in the process
#'
#' @param con A database connection
#' @param name Name of the table to write to
#' @param dta A data frame or sf data frame
#' @param overwrite If `TRUE`, overwrite an existing table
#' @param append If `TRUE`, append to an existing table
#' @param spatial If `TRUE`, write as spatial data
#' @param field_meta An optional data frame matching the structure for field metadata generated by `create_metadata_tables()`
#' @param table_meta An optional data frame matching the structure for table metadata generated by `create_metadata_tables()`
#' @param source_meta An optional data frame matching the structure for source metadata generated by `create_metadata_tables()`
#'
#' @export
#'
#' @importFrom sf st_write
#' @importFrom DBI dbWriteTable
#'

write_db <- function(con, name, dta, overwrite = FALSE, append = FALSE, spatial = FALSE, field_meta = NULL, table_meta = NULL, source_meta = NULL){

  if (spatial){

    if (!'sf' %in% class(dta)){
      stop('`spatial` is TRUE, but `dta` is not of class sf', call. = FALSE)
    }

    sf::st_write(dta, con, name, delete_dsn = overwrite, append = append)
  }

  if (!spatial){
    DBI::dbWriteTable(con, name, dta, overwrite = overwrite, append = append)
  }

  if (!is.null(field_meta) | !is.null(table_meta)){

    # if (is.null(table_meta)){
    #   stop("Both field and table metadata are required to update metadata")
    # }

    update_metadata(con, field_meta, table_meta, source_meta)

  }

  return(invisible(name))

}


#' Write data to the database. But ask before!
#'
#' Do not work with spatial data! 
#' Use connect_to_db() default hence write to data instance
#'
#' @param schema a schema in DB
#' @export
#'
#' @importFrom DBI dbWriteTable
#' @importFrom DBI dbDisconnect
#' @examples
#'
#' \dontrun{
#'  # it is a function factory so first step is creating the function
#'  write_staging <- can_i_write_table("staging")
#'  # then using it
#'  write_staging("mtcars", mtcars, overwrite = TRUE)
#' }

can_i_write_table <- function(schema) {
  force(schema)
  function(table_name, dat, ...) {

    check <-readline(prompt = sprintf("Are you sure you want to overwrite %s in the database? (yes/no): ", table_name))

    if (check != "yes") {
      stop("Turkey!")
    } else {
      con <- cori.db::connect_to_db(schema)
      on.exit(DBI::dbDisconnect(con), add = TRUE)
      DBI::dbWriteTable(con, table_name, dat, ...)
    }
  }
}